version: 0.2

        
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo install
   
  pre_build:
    commands:
      - echo pre_build
    
  build:
    commands:
      - mvn clean install
      - echo build
     
  post_build:
    commands:
      - echo post_build
      

artifacts:
  files:
    - target/AltimetrikGreetings-0.0.1-SNAPSHOT.war
 